# Generated by Django 5.2.2 on 2025-06-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_reviews',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
